import { CSSProperties } from 'react'

const openmoji_svg_color = import.meta.glob('./openmoji-svg-color/*.svg')

const emojis = [
  '🍏',
  '🍎',
  '🍊',
  '🍋',
  '🥭',
  '🍅',
  '🫒',
  '🧄',
  '🥔',
  '🥚',
  '🥧',
  '🥠',
  '🍚',
  '🧊',
  '🍽',
  '🥣',
  '🫖',
  '🥛',
  '🍯',
  '🍿',
  '🍫',
  '🍮',
  '🎂',
  '🍵',
  '🍶',
  '🏓',
  '🔮',
  '🛎',
  '🪞',
  '🎈',
  '🏷',
  '📁',
  '🗂',
  '📒',
  '🔒',
] as const

const faceOffsets: { [k in typeof emojis[number]]: Partial<{ style: CSSProperties }> } = {
  '🍏': {},
  '🍎': {},
  '🍊': {},
  '🍋': {},
  '🥭': {},
  '🍅': {},
  '🫒': {},
  '🧄': { style: { marginTop: '10%' } },
  '🥔': {},
  '🥚': {},
  '🥧': { style: { marginTop: '2%' } },
  '🥠': { style: { marginTop: '-8%', marginLeft: '5%' } },
  '🍚': { style: { marginTop: '10%' } },
  '🧊': { style: { marginLeft: '16%' } },
  '🍽': {},
  '🥣': { style: { marginTop: '10%' } },
  '🫖': { style: { marginTop: '5%', marginLeft: '-5%' } },
  '🥛': {},
  '🍯': { style: { marginTop: '10%', marginLeft: '-5%' } },
  '🍿': {},
  '🍫': { style: { marginTop: '10%' } },
  '🍮': { style: { marginTop: '10%' } },
  '🎂': { style: { marginTop: '-8%' } },
  '🍵': { style: { marginLeft: '10%' } },
  '🍶': { style: { marginTop: '10%', marginLeft: '19%' } },
  '🏓': { style: { marginTop: '-10%', marginLeft: '2%' } },
  '🔮': {},
  '🛎': { style: { marginTop: '-10%' } },
  '🪞': {},
  '🎈': { style: { marginTop: '-10%', marginLeft: '9%' } },
  '🏷': {},
  '📁': {},
  '🗂': { style: { marginTop: '5%' } },
  '📒': {},
  '🔒': { style: { marginTop: '7%' } },
} as const

export { openmoji_svg_color, emojis, faceOffsets }
