import { MouthKind } from './mouths'

const openmoji_svg_color = import.meta.glob('./openmoji-svg-color/*.svg')

const playerEmojis = [
  '😀',
  '😃',
  '😄',
  '😁',
  '😆',
  '😅',
  '😂',
  '🤣',
  '🥲',
  '☺️',
  '😊',
  '😇',
  '🙂',
  '🙃',
  '😉',
  '😌',
  '😍',
  '🥰',
  '😘',
  '😗',
  '😙',
  '😚',
  '😋',
  '😛',
  '😝',
  '😜',
  '🤪',
  '🤨',
  '🧐',
  '🤓',
  '😎',
  '🥸',
  '🤩',
  '🥳',
  '😏',
  '😒',
  '😞',
  '😔',
  '😟',
  '😕',
  '🙁',
  '☹️',
  '😣',
  '😖',
  '😫',
  '😩',
  '🥺',
  '😢',
  '😭',
  '😤',
  '😠',
  '🤯',
  '😳',
  '😶‍🌫️',
  '😱',
  '😨',
  '😰',
  '😥',
  '😓',
  '🤗',
  '🤔',
  '🤭',
  '🤫',
  '🤥',
  '😶',
  '😐',
  '😑',
  '😬',
  '🙄',
  '😯',
  '😦',
  '😧',
  '😮',
  '😲',
  '🥱',
  '😴',
  '🤤',
  '😪',
  '😮‍💨',
  '😵',
  '😵‍💫',
  '🤐',
  '🥴',
  '🤧',
  '😷',
  '🤒',
  '🤕',
  '🤑',
  '🤠',
] as const

const itemEmojis = ['❤', '🗺️', '🧭', '📦', '🪙'] as const

const npcEmojis = [
  '⭐️',
  '🍳',
  '🧀',
  '🥯',
  '🌰',
  '🍞',
  '🥜',
  '🍄',
  '🥦',
  '🥬',
  '🫑',
  '🌶️',
  '🌽',
  '🥑',
  '🥥',
  '🥝',
  '🫐',
  '🍒',
  '🍍',
  '🍃',
  '🍂',
  '🍁',
  '🍀',
  '☘️',
  '🌵',
  '🌳',
  '🌲',
  '🪴',
  '🌷',
  '🌼',
  '🐚',
  '🐣',
  '🛌',
  '👄',
  '🦷',
  '💭',
  '🗯️',
  '🗨️',
  '💣',
  '💦',
  '💥',
  '🤍',
  '🤎',
  '💜',
  '💙',
  '💚',
  '💛',
  '🧡',
  '❤️',
  '❤️‍🩹',
  '❤️‍🔥',
  '❣️',
  '💟',
  '💕',
  '💞',
  '💓',
  '💗',
  '💖',
  '💘',
  '👽',
  '💀',
  '☠️',
  '👻',
  '🍏',
  '🍎',
  '🍊',
  '🍋',
  '🥭',
  '🍅',
  '🫒',
  '🧄',
  '🥔',
  '🥚',
  '🥧',
  '🥠',
  '🍚',
  '🧊',
  '🍽',
  '🥣',
  '🫖',
  '🥛',
  '🍯',
  '🍿',
  '🍫',
  '🍮',
  '🎂',
  '🍵',
  '🍶',
  '🏓',
  '🔮',
  '🛎',
  '🪞',
  '🎈',
  '🏷',
  '📁',
  '🗂',
  '📒',
  '🔒',
] as const

const emojis = [...playerEmojis, ...itemEmojis, ...npcEmojis] as const

type PlayerEmoji = typeof playerEmojis[number]
type ItemEmoji = typeof itemEmojis[number]
type NPCEmoji = typeof npcEmojis[number]
type Emoji = typeof emojis[number]

const faceOverrides: Partial<{
  [k in Emoji]: Partial<{ x: number; y: number; eyeDistance: number; mouth: MouthKind }>
}> = {
  '🍳': { y: 22.5, mouth: 'D' },
  '🧀': { y: -17 },
  '🥯': { x: -1, y: 12.5, eyeDistance: -6, mouth: '3' },
  '🌰': { x: 2, y: 3, eyeDistance: -3 },
  '🍞': { x: -20 },
  '🥜': { x: -13, y: 15, eyeDistance: -5 },
  '🍄': { x: -0.5, y: 16, eyeDistance: -7 },
  '🥦': { y: -5 },
  '🥬': { x: 3, y: -11, eyeDistance: -5 },
  '🫑': { x: 6.5, y: 9.5 },
  '🌶️': { x: 26, y: 1.5, eyeDistance: -10 },
  '🌽': { x: -10.5, y: -6, eyeDistance: -5 },
  '🥑': { x: 0.5, y: -18, eyeDistance: -9 },
  '🥥': { x: -7, y: -7 },
  '🥝': { y: 1, eyeDistance: -8 },
  '🫐': { x: 14, y: 22 },
  '🍒': { x: -10, y: 24, eyeDistance: -5 },
  '🍍': { y: 17, x: -2, eyeDistance: -4 },
  '🍃': { y: 1.5 },
  '🍂': { x: -15, y: -9, eyeDistance: -5 },
  '🍁': { y: 8 },
  '🍀': { x: 4, y: -10, eyeDistance: -10 },
  '☘️': { x: 2, y: -4, eyeDistance: -5 },
  '🌵': { eyeDistance: -10 },
  '🌳': { y: -13 },
  '🪴': { x: -0.5, y: 21, eyeDistance: -6 },
  '🌷': { x: 16, y: 2, eyeDistance: -6 },
  '🌼': { x: 8, y: -2, mouth: '7' },
  '🐚': { x: 3.5, y: 4, eyeDistance: -6 },
  '🐣': { y: 20 },
  '🛌': { y: -2 },
  '👄': { y: -12 },
  '💣': { x: -10, y: 5 },
  '💦': { x: -17, y: 10 },
  '💥': { x: -3, y: 2, eyeDistance: -5 },
  '❤️‍🩹': { y: 12 },
  '❤️‍🔥': { x: -3, y: 7, eyeDistance: -3 },
  '❣️': { y: -15 },
  '💟': { y: 0 },
  '💕': { x: -12.5, y: 7 },
  '💞': { x: -12.5, y: 7 },
  '💓': { y: -4 },
  '💗': { y: 3 },
  '💖': { x: 1, y: -6 },
  '💘': { y: -10 },
  '👽': { y: -10 },
  '💀': { y: -10 },
  '☠️': { y: -10 },
  '👻': { y: 10 },
  '🧄': { y: 10 },
  '🥧': { y: 2 },
  '🥠': { x: 5, y: -8 },
  '🍚': { y: 10 },
  '🧊': { x: 16 },
  '🥣': { y: 10 },
  '🫖': { x: -5, y: 5 },
  '🍯': { x: -5, y: 10 },
  '🍫': { y: 10 },
  '🍮': { y: 10 },
  '🎂': { y: -8 },
  '🍵': { x: 10 },
  '🍶': { x: 19, y: 10 },
  '🏓': { x: 2, y: -10 },
  '🛎': { y: -10 },
  '🎈': { x: 9, y: -10 },
  '🗂': { y: 5 },
  '🔒': { y: 7 },
} as const

type MapItemOverrideProps = Partial<{
  className: string
  scale: number
  animation: string
  sound: string
  animationDuration: number
}>

const mapItemOverrides: Partial<{
  [k in Emoji]: MapItemOverrideProps
}> = {
  '🪙': { scale: 0.25, animation: 'animate-twist-fast', sound: 'coin.wav', animationDuration: 750 },
}

type FaceOverride = keyof typeof faceOverrides
type MapItemOverride = keyof typeof mapItemOverrides

export type { PlayerEmoji, ItemEmoji, NPCEmoji, Emoji, FaceOverride, MapItemOverrideProps, MapItemOverride }
export { openmoji_svg_color, emojis, faceOverrides, mapItemOverrides }
